- name: Update the package lists and install nginx.
  apt:
    name: nginx
    update_cache: true
    state: present
- name: Start the nginx server.
  systemd:
    name: nginx
    enabled: yes
    state: started
- name: Allow traffic through firewall
  ufw:
    default: allow
    name: nginx full
    state: enabled
